/**
 * Compliance PDF Generator
 * Generates printable documents using a print-optimized iframe.
 * No external dependencies required.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyRecord = Record<string, any>;

const BRAND_CSS = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    color: #1a1a1a; font-size: 12px; line-height: 1.5;
    padding: 20mm 15mm;
  }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px; border-bottom: 3px solid #10B981; padding-bottom: 15px; }
  .logo { font-size: 24px; font-weight: 800; color: #10B981; }
  .logo-sub { font-size: 10px; color: #666; margin-top: 2px; }
  .doc-title { font-size: 18px; font-weight: 700; text-align: right; }
  .doc-subtitle { font-size: 10px; color: #666; text-align: right; }
  .section { margin-bottom: 16px; }
  .section-title { font-size: 13px; font-weight: 700; color: #10B981; margin-bottom: 8px; border-bottom: 1px solid #e5e5e5; padding-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
  th, td { padding: 6px 10px; text-align: left; border: 1px solid #ddd; font-size: 11px; }
  th { background: #f5f5f5; font-weight: 600; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 10px; font-weight: 700; }
  .badge-pass { background: #D1FAE5; color: #059669; }
  .badge-fail { background: #FEE2E2; color: #DC2626; }
  .badge-risk { background: #FEF3C7; color: #D97706; }
  .footer { margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px; font-size: 9px; color: #999; text-align: center; }
  .total-row { font-weight: 700; background: #f9fafb; }
  @media print { body { padding: 10mm; } }
`;

function printHTML(title: string, bodyHTML: string): void {
    const iframe = document.createElement('iframe');
    iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:0;height:0;';
    document.body.appendChild(iframe);

    const doc = iframe.contentDocument || iframe.contentWindow?.document;
    if (!doc) return;

    doc.open();
    doc.write(`<!DOCTYPE html><html><head><title>${title}</title><style>${BRAND_CSS}</style></head><body>${bodyHTML}</body></html>`);
    doc.close();

    setTimeout(() => {
        iframe.contentWindow?.print();
        setTimeout(() => document.body.removeChild(iframe), 1000);
    }, 250);
}

function formatDate(d: string | null): string {
    if (!d) return '—';
    return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
}

// --- CP12 Gas Safety Record ---
export function generateCP12PDF(record: AnyRecord): void {
    const resultBadge = record.overall_result === 'Pass' ? 'badge-pass' : record.overall_result === 'Fail' ? 'badge-fail' : 'badge-risk';
    const appliances = Array.isArray(record.appliances) ? record.appliances : [];

    const html = `
        <div class="header">
            <div><div class="logo">Gas Genie</div><div class="logo-sub">Gas Safety Record</div></div>
            <div><div class="doc-title">Landlord Gas Safety Record</div><div class="doc-subtitle">Gas Safety (Installation and Use) Regulations 1998</div></div>
        </div>

        <div class="section">
            <div class="section-title">Property & Persons</div>
            <table>
                <tr><th>Property Address</th><td>${record.property_address || '—'}</td></tr>
                <tr><th>Landlord</th><td>${record.landlord_name || '—'}</td></tr>
                <tr><th>Tenant</th><td>${record.tenant_name || '—'}</td></tr>
                <tr><th>Inspection Date</th><td>${formatDate(record.inspection_date)}</td></tr>
                <tr><th>Next Due</th><td>${formatDate(record.next_due)}</td></tr>
                <tr><th>Overall Result</th><td><span class="badge ${resultBadge}">${record.overall_result}</span></td></tr>
            </table>
        </div>

        ${appliances.length > 0 ? `
        <div class="section">
            <div class="section-title">Appliances Inspected</div>
            <table>
                <tr><th>Appliance</th><th>Location</th><th>Make/Model</th><th>Flue Type</th><th>Result</th></tr>
                ${appliances.map((a: AnyRecord) => `
                    <tr>
                        <td>${a.type || '—'}</td>
                        <td>${a.location || '—'}</td>
                        <td>${a.make || ''} ${a.model || ''}</td>
                        <td>${a.flue_type || '—'}</td>
                        <td><span class="badge ${a.result === 'Pass' ? 'badge-pass' : a.result === 'Fail' ? 'badge-fail' : 'badge-risk'}">${a.result || '—'}</span></td>
                    </tr>
                `).join('')}
            </table>
        </div>
        ` : ''}

        <div class="footer">
            Generated by Gas Genie • ${new Date().toLocaleDateString('en-GB')} • This is a digital record
        </div>
    `;

    printHTML('CP12 Gas Safety Record', html);
}

// --- Quote PDF ---
export function generateQuotePDF(quote: AnyRecord): void {
    const items = Array.isArray(quote.items) ? quote.items : [];

    const html = `
        <div class="header">
            <div><div class="logo">Gas Genie</div><div class="logo-sub">Quotation</div></div>
            <div><div class="doc-title">${quote.quote_number || 'QUOTE'}</div><div class="doc-subtitle">Status: ${quote.status || 'Draft'}</div></div>
        </div>

        <div class="section">
            <table>
                <tr><th>Date</th><td>${formatDate(quote.created_at)}</td><th>Valid Until</th><td>${formatDate(quote.valid_until)}</td></tr>
            </table>
        </div>

        <div class="section">
            <div class="section-title">Items</div>
            <table>
                <tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>
                ${items.map((item: AnyRecord) => `
                    <tr>
                        <td>${item.description || '—'}</td>
                        <td>${item.quantity || 1}</td>
                        <td>£${(item.unit_price || 0).toFixed(2)}</td>
                        <td>£${((item.quantity || 1) * (item.unit_price || 0)).toFixed(2)}</td>
                    </tr>
                `).join('')}
                <tr><td colspan="3"><strong>Labour</strong> (${quote.labour_hours || 0} hrs × £${quote.labour_rate || 60}/hr)</td><td>£${((quote.labour_hours || 0) * (quote.labour_rate || 60)).toFixed(2)}</td></tr>
                <tr class="total-row"><td colspan="3">Subtotal</td><td>£${(quote.subtotal || 0).toFixed(2)}</td></tr>
                <tr class="total-row"><td colspan="3">VAT (20%)</td><td>£${(quote.vat || 0).toFixed(2)}</td></tr>
                <tr class="total-row"><td colspan="3"><strong>Total</strong></td><td><strong>£${(quote.total || 0).toFixed(2)}</strong></td></tr>
            </table>
        </div>

        <div class="footer">
            Generated by Gas Genie • ${new Date().toLocaleDateString('en-GB')}
        </div>
    `;

    printHTML(`Quote ${quote.quote_number || ''}`, html);
}

// --- Invoice PDF ---
export function generateInvoicePDF(invoice: AnyRecord): void {
    const items = Array.isArray(invoice.items) ? invoice.items : [];

    const html = `
        <div class="header">
            <div><div class="logo">Gas Genie</div><div class="logo-sub">Invoice</div></div>
            <div><div class="doc-title">${invoice.invoice_number || 'INVOICE'}</div><div class="doc-subtitle">Status: ${invoice.status || 'Unpaid'} • Due: ${formatDate(invoice.due_date)}</div></div>
        </div>

        <div class="section">
            <div class="section-title">Items</div>
            <table>
                <tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>
                ${items.map((item: AnyRecord) => `
                    <tr>
                        <td>${item.description || '—'}</td>
                        <td>${item.quantity || 1}</td>
                        <td>£${(item.unit_price || 0).toFixed(2)}</td>
                        <td>£${((item.quantity || 1) * (item.unit_price || 0)).toFixed(2)}</td>
                    </tr>
                `).join('')}
                <tr><td colspan="3"><strong>Labour</strong> (${invoice.labour_hours || 0} hrs × £${invoice.labour_rate || 60}/hr)</td><td>£${((invoice.labour_hours || 0) * (invoice.labour_rate || 60)).toFixed(2)}</td></tr>
                <tr class="total-row"><td colspan="3">Subtotal</td><td>£${(invoice.subtotal || 0).toFixed(2)}</td></tr>
                <tr class="total-row"><td colspan="3">VAT (20%)</td><td>£${(invoice.vat || 0).toFixed(2)}</td></tr>
                <tr class="total-row"><td colspan="3"><strong>Total Due</strong></td><td><strong>£${(invoice.total || 0).toFixed(2)}</strong></td></tr>
            </table>
        </div>

        <div class="section">
            <p style="font-size: 10px; color: #666;">Payment terms: 30 days from invoice date. Please reference invoice number with payment.</p>
        </div>

        <div class="footer">
            Generated by Gas Genie • ${new Date().toLocaleDateString('en-GB')}
        </div>
    `;

    printHTML(`Invoice ${invoice.invoice_number || ''}`, html);
}
